server:
  port: 9500

spring:
  application:
    name: dw-chat
  ai:
    dashscope:
      api-key:
      chat:
        options:
          model: 'qwen-max'


# log等级
logging:
  config: classpath:logback/logback-spring.xml
  level:
    org.springframework.ai.chat.client.advisor: debug


